### PR TITLE
Object fallbacks

### PR DESCRIPTION
**Pull request by sauramirez**
Pull request for issue #9

### CODE REVIEW

**Comment by ctavan** [comment]
@sauramirez sorry for the long delay.

I really like your pull request! In particular the fact that the feature remains disabled by default (so it backwards compatible) and can be activated on demand.

However I would like to ask you two more things:
1. Have you checked if it works with `getenv.multi()` as well? Could you add a test?
2. As this module is currently well documented in the README please document the added features there as well. You can of course also add yourself to the list of contributors if you want.

Once these 2 points are clarified I'm happy to merge the pull request and upload a new package to NPM.

**Comment by sauramirez** [comment]
Oh right I'll add tests for multi and the appropriate documentation.

**Comment by ctavan** [comment]
That's great!

**Comment by sauramirez** [comment]
Any update on this?

**Comment by ctavan** [comment]
@sauramirez I've checked the code again and I would like to make another suggestion: I think – although used pretty widely – relying on the magic environment `NODE_ENV` is not so nice. Instead I would suggest passing the environment into the `enableObjectFallback()` method.

So you would do something like:

```js
// assuming: process.env.NODE_ENV === 'development';
getenv.enableObjectFallback(process.env.NODE_ENV);
```

So whatever is passed into `getenv.enableObjectFallback()` as first argument would be used for the object fallback lookups.

What do you think about that?

**Comment by sauramirez** [comment]
I like that idea since it provides less implicit behavior. I've implemented that change in the PR.

**Comment by ctavan** [comment]
Closing this as there has not been any activity for a long time. If you still feel this is relevant @sauramirez please don't hesitate to reopen.

**Pull request closed without merging**
