### PR TITLE
Adding boolish support

### PR DESCRIPTION
**Pull request by chrisnojima**
Typically I'd use a flag but it seems like it'd be messy to plumb it all the way through, so I'm going with the simple boolish for now.

### CODE REVIEW

**Comment by ctavan** [comment]
Cool! Thanks a lot! Could you squash the two commits? I'm happy to merge it then.

**Comment by chrisnojima** [comment]
Done

**Comment by ctavan** [comment]
Sorry for bugging you again, but would you consider adding 2 test cases similar to https://github.com/ctavan/node-getenv/blob/master/test/getenv.js#L193-L222 ? That would make the features complete and tested.

**Comment by chrisnojima** [comment]
Done

**Comment by ctavan** [comment]
Published to npm as 0.6.0

**Comment by ctavan** [comment]
Thank you @chrisnojima !

**Pull request merged**
